=== BlueQuartzSoftware/MXADataModel/Resources/XML/mxa_0.4.dtd
<!-- This is the DTD file for the MXADataModel code base -->
<!ELEMENT File_Root (Data_Model,Meta_Data,Support_Files*)>
<!ELEMENT Data_Model (Data_Root,Data_Dimensions,Data_Records)>
<!ELEMENT Data_Root EMPTY>
<!ELEMENT Data_Dimensions (Dimension)+>
<!ELEMENT Dimension EMPTY>
<!ELEMENT Data_Records (Signal|Signal_Group)+>
<!ELEMENT Signal EMPTY>
<!ELEMENT Signal_Group (Signal|Signal_Group)+>
<!ELEMENT Meta_Data (Required_MD,UserDefined_MD)>
<!ELEMENT Required_MD EMPTY>
<!ELEMENT UserDefined_MD (UserMetaData)*>
<!ELEMENT Support_Files (Support_File)*>

<!ATTLIST Data_Root Name CDATA #REQUIRED>
<!ATTLIST Data_Model 
    Model_Type CDATA #REQUIRED
    Model_Version CDATA #REQUIRED>
<!ATTLIST Dimension 
    Name CDATA #REQUIRED
    Alt_Name CDATA #REQUIRED
    Count CDATA #IMPLIED
    End_Value CDATA #IMPLIED
    Increment CDATA #IMPLIED
    Index CDATA #IMPLIED
    Start_Value CDATA #IMPLIED
    Uniform CDATA #IMPLIED>
<!ATTLIST Signal 
    Name CDATA #REQUIRED
    Alt_Name CDATA #REQUIRED>
<!ATTLIST Signal_Group 
    Name CDATA #REQUIRED
    Alt_Name CDATA #REQUIRED>
<!ATTLIST Required_MD 
    Creator CDATA #REQUIRED
    Date CDATA #REQUIRED
    Name CDATA #REQUIRED
    Description CDATA #REQUIRED
    Pedigree (Original|Derived) "Original" 
    Original_Source_File CDATA "Not Applicable"
    Distribution_Rights (Limited|Unlimited) "Unlimited"
    Release_Limitation CDATA "Not Applicable"
    Release_Number CDATA "Not Applicable">
 
<!ATTLIST UserMetaData
    key CDATA #REQUIRED
    dims CDATA #REQUIRED
    type (H5T_STRING|H5T_NATIVE_INT8|H5T_NATIVE_INT16|H5T_NATIVE_INT32|H5T_NATIVE_INT64|H5T_NATIVE_UINT8|H5T_NATIVE_UINT16|H5T_NATIVE_UINT32|H5T_NATIVE_UINT64|H5T_NATIVE_FLOAT|H5T_NATIVE_DOUBLE) "H5T_NATIVE_INT32"
    >
<!ATTLIST Support_File
  FileSystem_Path CDATA #REQUIRED
  File_Type (Text|Binary) "Binary">

=== BlueQuartzSoftware/MXADataModel/Resources/ModelTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE File_Root SYSTEM "http://titanium.imts.us/viewvc/Task_7/MXADataModel/Resources/mxa_0.4.dtd">
<File_Root>
  <Data_Model Model_Type="MXA" Model_Version="0.4">
    <Data_Root Name="DataModelTest/Data/Root/Is/Here/" />
    <Data_Dimensions>
        <Dimension Alt_Name="Vol Frac" Count="16" End_Value="50" Increment="2" Index="0" Name="Dim 0" Start_Value="20" Uniform="1" />
        <Dimension Alt_Name="Rnd Seed" Count="9" End_Value="5000" Increment="500" Index="1" Name="Dim 1" Start_Value="1000" Uniform="1" />
        <Dimension Alt_Name="TS" Count="100" End_Value="99" Increment="1" Index="2" Name="Dim 2" Start_Value="0" Uniform="1" />
        <Dimension Alt_Name="slice" Count="256" End_Value="255" Increment="1" Index="3" Name="Dim 3" Start_Value="0" Uniform="1" />
    </Data_Dimensions>
    <Data_Records>
        <Signal Alt_Name="Record 0" Name="Record 0" />
    </Data_Records>
  </Data_Model>
  <Meta_Data>
    <Required_MD Creator="Mike Jackson" 
    Date="June 25 2005" 
    Description="These are images that were created during a FIB experiment" 
    Distribution_Rights="Publicly Released" 
    Name="Junk Test Data" 
    Original_Source_File="Individual tiff images and ANG files collected from the instrument" 
    Pedigree="Generated at WPAFB/AFRL/MLLM" 
    Release_Number="WS-AFRL-12300IDNVD" />
    <UserDefined_MD>
  </UserDefined_MD>
  </Meta_Data>
</File_Root>

=== BlueQuartzSoftware/MXADataModel/Resources/XML/ModelTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE File_Root SYSTEM "http://echo1.bluequartz.net/viewvc/CTMD/MXADataModel/Resources/XML/mxa_0.4.dtd">
<File_Root>
  <Data_Model Model_Type="MXA" Model_Version="0.4">
    <Data_Root Name="DataModelTest/Data/Root/Is/Here/" />
    <Data_Dimensions>
        <Dimension Alt_Name="Vol Frac" Count="16" End_Value="50" Increment="2" Index="0" Name="Dim_0" Start_Value="20" Uniform="1" />
        <Dimension Alt_Name="Rnd Seed" Count="9" End_Value="5000" Increment="500" Index="1" Name="Dim_1" Start_Value="1000" Uniform="1" />
        <Dimension Alt_Name="TS" Count="100" End_Value="99" Increment="1" Index="2" Name="Dim_2" Start_Value="0" Uniform="1" />
        <Dimension Alt_Name="slice" Count="256" End_Value="255" Increment="1" Index="3" Name="Dim_3" Start_Value="0" Uniform="1" />
    </Data_Dimensions>
    <Data_Records>
        <Signal Alt_Name="Record 0" Name="Record 0" />
    </Data_Records>
  </Data_Model>
  <Meta_Data>
    <Required_MD Creator="Mike Jackson" 
    Date="June 25 2007" 
    Description="Some description of your experiment or data set" 
    Distribution_Rights="Unlimited" 
    Name="Test Data" 
    Original_Source_File="Description of where the data comes from: Directly from the Instrument or from files on disk." 
    Pedigree="Original" 
    Release_Number="Not Applicable" />

    <UserDefined_MD/>
  </Meta_Data>
</File_Root>
